from .block_hamiltonian_losses import block_occurrence_clean_loss, block_occurrence_rmse_by_chart
from .ema import ExponentialMovingAverage
from .hamiltonian_field_losses import midpoint_secant_loss
from .hmsrf_losses import HMSRFLossOutput, hmsrf_loss
from .hamiballs_formal import HamiBallsAnisotropicIRLSRelationObjective, HamiBallsChannelSeparatedRelationObjective, HamiBallsDeployPConsistencyObjective, HamiBallsHardHealthAudit, HamiBallsPseudoAnchorResult, audit_hamiballs_hard_health, canonical_state_scale, closed_loop_gate_mse, convex_oracle_gate, hamiballs_anisotropic_irls_relation_loss, hamiballs_channel_separated_relation_loss, hamiballs_deploy_p_consistency_loss, hamiballs_free_rollout_loss, hamiballs_identity_relation_residual_scale, hamiballs_relation_loss, identity_hamiballs_affine_jets, learned_hamiballs_affine_jets, normalise_object_context, pointwise_gate_mse, previous_gate_sequence, rollout_with_affine_jets, set_module_trainable, two_sweep_pseudo_anchor
from .hamiballs_d import HamiBallsDUpdate, build_hamiballs_d, d_clean_and_tokens, matched_wide_inner_dim, nested_wide_from_narrow, parameter_count, update_hamiballs_d
from .training_schedule import ExplicitEpochBatchStream, cosine_learning_rate, generator_state_dict, load_generator_state_dict, set_optimizer_learning_rate
from .trainer import HamiFormerTrainer
from .wavefront_losses import wavefront_active_clean_loss
from .oneway_gf_tangent import OneWayGFTangentRollout, OnPolicyTeacherRollout, TrainableHObjective, annealed_teacher_responsibility, linear_teacher_strength, mixed_hessian_barrier, oneway_gf_tangent_rollout, onpolicy_convex_teacher_rollout, responsibility_with_floor, trainable_h_objective, weighted_type2_relation_loss
OneWayGFJPRollout = OneWayGFTangentRollout
oneway_gfjp_rollout = oneway_gf_tangent_rollout
OneWayLGFRollout = OneWayGFTangentRollout
oneway_lgf_scan_rollout = oneway_gf_tangent_rollout
__all__ = ['ExponentialMovingAverage', 'HamiFormerTrainer', 'HMSRFLossOutput', 'block_occurrence_clean_loss', 'block_occurrence_rmse_by_chart', 'midpoint_secant_loss', 'hmsrf_loss', 'wavefront_active_clean_loss', 'OneWayGFTangentRollout', 'OneWayGFJPRollout', 'OneWayLGFRollout', 'OnPolicyTeacherRollout', 'TrainableHObjective', 'annealed_teacher_responsibility', 'linear_teacher_strength', 'mixed_hessian_barrier', 'oneway_gf_tangent_rollout', 'oneway_gfjp_rollout', 'oneway_lgf_scan_rollout', 'onpolicy_convex_teacher_rollout', 'responsibility_with_floor', 'trainable_h_objective', 'weighted_type2_relation_loss', 'HamiBallsPseudoAnchorResult', 'HamiBallsAnisotropicIRLSRelationObjective', 'HamiBallsChannelSeparatedRelationObjective', 'HamiBallsDeployPConsistencyObjective', 'HamiBallsHardHealthAudit', 'audit_hamiballs_hard_health', 'canonical_state_scale', 'closed_loop_gate_mse', 'convex_oracle_gate', 'hamiballs_anisotropic_irls_relation_loss', 'hamiballs_channel_separated_relation_loss', 'hamiballs_deploy_p_consistency_loss', 'hamiballs_free_rollout_loss', 'hamiballs_identity_relation_residual_scale', 'hamiballs_relation_loss', 'identity_hamiballs_affine_jets', 'learned_hamiballs_affine_jets', 'normalise_object_context', 'pointwise_gate_mse', 'previous_gate_sequence', 'rollout_with_affine_jets', 'set_module_trainable', 'two_sweep_pseudo_anchor', 'HamiBallsDUpdate', 'build_hamiballs_d', 'd_clean_and_tokens', 'matched_wide_inner_dim', 'nested_wide_from_narrow', 'parameter_count', 'update_hamiballs_d', 'ExplicitEpochBatchStream', 'cosine_learning_rate', 'generator_state_dict', 'load_generator_state_dict', 'set_optimizer_learning_rate']
